### ISSUE TITLE
Deinit cause crash when `cameraDevice = .front`

### ISSUE THREAD

**Issue by TienVu-PW** [imaginary-cloud/CameraManager#157]
Hi, seems like the `self.cameraDevice = .back` inside `stopAndRemoveCaptureSession()` in `deinit` is causing crash if the `cameraDevice` is `.front`, I have to manually calling `stopAndRemoveCaptureSession()` in my viewController to stop it before dismiss the viewController.

Please check this issue, thank you.

**Comment by davinic** [comment]
+1

**Comment by davinic** [comment]
I was able to work around this by setting `cameraManager.shouldKeepViewAtOrientationChanges = true`, since the issue is happening in the async closure at:

https://github.com/imaginary-cloud/CameraManager/blob/b0075ed1d8af926d65988dd44883c23c4257ff15/camera/CameraManager.swift#L1097

The specific runtime error is : `Thread 1: EXC_BAD_ACCESS (code=1, address=0x20)`

**Comment by torrao** [comment]
@TienVu-PW and @davidortinau,

we are currently looking at this issue. Thanks for the feedback 👍

**Comment by lucasmpaim** [comment]
+1

**Comment by torrao** [comment]
@TienVu-PW @davinic @lucasmpaim,

this issue should be fixed in [v.4.2.3](https://github.com/imaginary-cloud/CameraManager/tree/4.2.3). 
Please let me know if it worked.

**Comment by TienVu-PW** [comment]
@torrao Seems to be working fine now, thanks!
